config/routes.rb
Biblioteca::Application.routes.draw do
  resources :sobres

  resources :pessoas do
    resources :livros	
  end

  resources :products

  get "home/index"

  root :to => 'home#index'

  get "/:page" => "static#show"

end

app/models/livro.rb
class Livro < ActiveRecord::Base
  belongs_to :pessoa
  attr_accessible :autor, :descricao, :titulo
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  attr_accessible :cpf, :nome, :telefone
  validates :nome,  :presence => true
  validates :cpf,  :presence => true

  has_many :livros
	
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price
end

app/models/sobre.rb
class Sobre < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  def create
    @pessoa = Pessoa.find(params[:pessoa_id])
    @livro = @pessoa.livros.create(params[:livro])
    redirect_to pessoa_path(@pessoa)
  end	
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pessoas }
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/new
  # GET /pessoas/new.json
  def new
    @pessoa = Pessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/1/edit
  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(params[:pessoa])

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render json: @pessoa, status: :created, location: @pessoa }
      else
        format.html { render action: "new" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pessoas/1
  # PUT /pessoas/1.json
  def update
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      if @pessoa.update_attributes(params[:pessoa])
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sobres_controller.rb
class SobresController < ApplicationController
  # GET /sobres
  # GET /sobres.json
  def index
    @sobres = Sobre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sobres }
    end
  end

  # GET /sobres/1
  # GET /sobres/1.json
  def show
    @sobre = Sobre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sobre }
    end
  end

  # GET /sobres/new
  # GET /sobres/new.json
  def new
    @sobre = Sobre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sobre }
    end
  end

  # GET /sobres/1/edit
  def edit
    @sobre = Sobre.find(params[:id])
  end

  # POST /sobres
  # POST /sobres.json
  def create
    @sobre = Sobre.new(params[:sobre])

    respond_to do |format|
      if @sobre.save
        format.html { redirect_to @sobre, notice: 'Sobre was successfully created.' }
        format.json { render json: @sobre, status: :created, location: @sobre }
      else
        format.html { render action: "new" }
        format.json { render json: @sobre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sobres/1
  # PUT /sobres/1.json
  def update
    @sobre = Sobre.find(params[:id])

    respond_to do |format|
      if @sobre.update_attributes(params[:sobre])
        format.html { redirect_to @sobre, notice: 'Sobre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sobre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sobres/1
  # DELETE /sobres/1.json
  def destroy
    @sobre = Sobre.find(params[:id])
    @sobre.destroy

    respond_to do |format|
      format.html { redirect_to sobres_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_controller.rb
# static_controller.rb
class StaticController < ApplicationController
  def show
    render params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sobres_helper.rb
module SobresHelper
end

app/views/home/index.html.erb
<h1>Bem vindo!</h1> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Biblioteca</a>
        <div class="nav-collapse">
          <ul class="nav">
	    <li><%= link_to "Pessoas", pessoas_path %></li>
	    <li><%= link_to "Sobre", sobres_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
     
    </div>
    <img width="100" height="100" style="float: right;" src="/imagens/imagem.jpg"> 

  </div>
</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Lista de pessoas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Cpf</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= pessoa.cpf %></td>
    <td><%= pessoa.telefone %></td>
    <td><%= link_to 'Show', pessoa %></td>
    <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
    <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<%= link_to 'New Pessoa', new_pessoa_path %>
<br /><br />
<p> Clique em "Show" para exibir ou adicionar livros para cada pessoa</p>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pessoa.nome %>
</p>

<p>
  <b>Cpf:</b>
  <%= @pessoa.cpf %>
</p>

<p>
  <b>Telefone:</b>
  <%= @pessoa.telefone %>
</p>

<h2>Livros</h2>
<% @pessoa.livros.each do |livro| %>
  <p>
    <b>Titulo:</b>
    <%= livro.titulo %>
  </p>
  <p>
    <b>Autor:</b>
    <%= livro.autor %>
  </p>
  <p>
    <b>Descricao:</b>
    <%= livro.descricao %>
  </p>
<% end %>



<h2>Adicione um livro:</h2>
<%= form_for([@pessoa, @pessoa.livros.build]) do |f| %>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/sobre/_form.html.erb
<%= form_for @sobre, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sobre_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sobre/edit.html.erb
<%- model_class = Sobre -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sobre/index.html.erb
<%- model_class = Sobre -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sobres.each do |sobre| %>
      <tr>
        <td><%= link_to sobre.id, sobre_path(sobre) %></td>
        <td><%=l sobre.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sobre_path(sobre), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sobre_path(sobre),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sobre_path,
            :class => 'btn btn-primary' %>

app/views/sobre/new.html.erb
<%- model_class = Sobre -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sobre/show.html.erb
<%- model_class = Sobre -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sobre_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sobre_path(@sobre), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sobre_path(@sobre),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/sobres/_form.html.erb
<%= form_for(@sobre) do |f| %>
  <% if @sobre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sobre.errors.count, "error") %> prohibited this sobre from being saved:</h2>

      <ul>
      <% @sobre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sobres/edit.html.erb
<h1>Editing sobre</h1>

<%= render 'form' %>

<%= link_to 'Show', @sobre %> |
<%= link_to 'Back', sobres_path %>

app/views/sobres/index.html.erb
<h1>Sobre</h1>
<br/>
<br/>
<div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sobres.each do |sobre| %>
  <tr>
    <td><%= link_to 'Show', sobre %></td>
    <td><%= link_to 'Edit', edit_sobre_path(sobre) %></td>
    <td><%= link_to 'Destroy', sobre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/sobres/new.html.erb
<h1>New sobre</h1>

<%= render 'form' %>

<%= link_to 'Back', sobres_path %>

app/views/sobres/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sobre_path(@sobre) %> |
<%= link_to 'Back', sobres_path %>